version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-secure
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: SocialMedia@2025
    command: >
      sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: